### ISSUE TITLE
Can't ask for "always" permission when asked for "whenInUse" firstly

### ISSUE THREAD

**Issue by paweljankowski** [PromiseKit/CoreLocation#4] opened 2017-10-04 17:10 UTC
When I'm asking for `whenInUse` location permission then when I'm asking for `always` the promise is fulfilled with current status (`whenInUse`).

**Comment by mxcl** [comment] 2017-10-04 17:38
Yeah, will need updating for iOS 11 I guess. PR welcome.

**Comment by paweljankowski** [comment] 2017-10-04 19:16
@mxcl https://github.com/PromiseKit/CoreLocation/pull/5 :-)

**Comment by mxcl** [comment] 2018-01-10 16:12
I could use some more detailed instructions on how to reproduce this and what happens.

**Comment by bruno-rocha-movile** [comment] 2018-01-10 16:42
This method works consistently for me:
- Have a fresh install (or install where the `always` permission was never asked before)
- Call `CLLocationManager.promise(.whenInUse)` succesfully
- At some point later in your app, call `CLLocationManager.promise(.always)`

If you do this, the promotion dialog will show up but quickly close itself. This is because the promise will prematurely succeed due to the previously accepted `whenInUse` permission. The dialog closes because the location manager gets released right after the location is retrieved (which is correct, but in this case we want to wait for the user to act upon the dialog)

So to fix this, we have to identify if this is a promotion request and prevent releasing the manager before the dialog is closed. Since retaining the manager for eternity would probably be bad, this may require some thought

**Comment by mxcl** [comment] 2018-01-12 23:36
Please review above PR

**Comment by mxcl** [comment] 2018-02-13 22:11
Pretty please review the above PR. Thanks!

**Closed as completed** 2018-02-18 17:38 UTC
